name: fiap_retail_quality
version: "1.0.0"
config-version: 2

profile: fiap_retail_quality

model-paths: ["models"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  fiap_retail_quality:
    staging:
      +materialized: view
    marts:
      +materialized: table